esphome:
  name: heating

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "34thm6"

ota:
  password: "34thm6"

wifi:
  ssid: "NR12"
  password: "18ad800569"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heating Fallback Hotspot"
    password: "RZDNmxRasl8k"

captive_portal:

dallas:
  - pin: 4

sensor:
  - platform: dallas
    address: 0x7e0000000c6f6a28
    name: "Boiler Flow Temp"
  - platform: dallas
    address: 0xa20000000accab28
    name: "Boiler Return Temp"

binary_sensor:
  - platform: gpio
    device_class: heat
    name: "Boiler"
    icon: mdi:fire
    pin: 5
